# Source normal stuff as though this is a login shell

[ -r /etc/profile ] && . /etc/profile

# This environment can be customised using ~/.xmds/bash_profile
if [ -r "$HOME/.xmds/bash_profile" ]; then
    . "$HOME/.xmds/bash_profile";
fi

export XMDS_SHELL=YES

export DEVELOPER_DIR="${DEVELOPER_DIR}"
export XMDS_USR="${XMDS_USR}"
export XMDS_SUPPORT="${XMDS_SUPPORT}"

source "${XMDS_USR}/share/xmds/xmds.conf";

${ADDITIONAL_COMMANDS}