#!/usr/bin/env python

import sys

have_input_file = False

argv = sys.argv[1:]

while argv:
	if argv[0] in ["-arch", "-o", "-I"]:
		# Skip this and next tokens
		del argv[0:2]
		continue
	elif argv[0][0] == '-':
		# skip option token
		del argv[0]
		continue
	
	have_input_file = True
	break

import subprocess

args = ["/opt/local/bin/clang-mp-3.3", "-c", "-x", "assembler"] + sys.argv[1:]
if not have_input_file:
	args.append("-")

result = subprocess.call(args)
